### ISSUE TITLE
Cyclic Increasing Hearts Too Much

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Cyclic#1418]
Minecraft Version: 1.15.2
Forge Version: 31.1.74
Mod Version: 1.15.2-0.4.1
Single Player or Server: Both

ScalingHealth-1.15.2-3.0.5+52
SilentLib-1.15.2-4.6.1+49

**Describe problem (what you were doing; what happened; what should have happened):**

With Cyclic and ScalingHealth installed, when you die you gain double hearts - I used a ScalingHealth Heart Crystal to give me 1 extra heart - when I died I had 2 extra hearts - this does not happen when Cyclic is removed

This also happens when I use SOL:Carrot Edition - I ate 5 foods, gained 1 extra heart, when I died I had 2 extra hearts - again this does not happen when Cyclic removed

this has been reported to ScalingHealth (Not by me)  Issue: https://github.com/SilentChaos512/ScalingHealth/issues/268

**Comment by FireController1847** [comment]
Hey there! I'm the developer of the LevelHearts mod with an issue similar to this: https://gitlab.com/FireController1847/levelhearts/-/issues/21.

I've poked around your source code, @Lothrazar, and have determined the issue comes down to this line in your heart items: https://github.com/Lothrazar/Cyclic/blob/trunk/1.15/src/main/java/com/lothrazar/cyclic/item/HeartToxicItem.java#L31
https://github.com/Lothrazar/Cyclic/blob/trunk/1.15/src/main/java/com/lothrazar/cyclic/item/HeartItem.java#L31

I'm not entirely sure why you would do it this way instead of modifying *your* modifier (and not the base value of the main modifier), but I just thought this could help point you in the right direction for fixing this :)

**Comment by SayulilyonPipeDream** [comment]
I also have noticed this issue on my 1.15.2 server running Cyclic Verison 0.4.2. We are running with SOL: Carrot, which also adds hearts after eating items. However, we are able to (temporarily) fix the issue by tweaking the player's file and resetting their Cyclic Hearts. This lasts as long as players DON'T die, so we are eager for the update. :)

**Comment by Lothrazar** [comment]
@FireController1847  Thanks for the info , ive been away for a while but this looks like the issue. 

Would it get fixed if instead of getBaseValue  i got the local value?

**Comment by FireController1847** [comment]
Well, I haven't studied your source code, but as long as you are not modifying the base value, it should fix the issue.

**Comment by Lothrazar** [comment]
i made a fix for this by replacing all references to getBaseValue to just GetValue.  

I tried to load levelhearts in eclipse the same way that worked in 1.12 but i got a weird error. so ill just build and test outside 

`[20Jun2020 23:55:24.187] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: levelhearts, class com.firecontroller1847.levelhearts.LevelHearts
java.lang.NoSuchMethodError: net.minecraft.item.Item$Properties.func_200917_a(I)Lnet/minecraft/item/Item$Properties;
	at com.firecontroller1847.levelhearts.items.ItemHeartPiece.<init>(ItemHeartPiece.java:10) ~[?:?]
	at com.firecontroller1847.levelhearts.LevelHeartsItems.<clinit>(LevelHeartsItems.java:15) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?]`

**Comment by FireController1847** [comment]
Yeah, you can't test inside of the IDE post-1.12 anymore due to a bug that Minecraft Forge already knows about and isn't eager to fix anytime soon, so unfortunately you do have to test it in a production  environment

**Comment by Lothrazar** [comment]
ok with new code (will be 0.4.2, in forge 31.1.74)
use one LevelHearts container
use one cyclic container
have 12 hearts
go to nether and come back
still 12

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937

**Comment by ghost** [comment]
Thank you folks
