### ISSUE TITLE
Cyclic 1.7.11-13 does not work on MC1.18.2

### ISSUE THREAD

**Issue by jclendineng** [PrinceOfAmber/Cyclic#2191]
Minecraft Version: 1.18.2

Forge Version: 40.1.80

Mod Version: 1.7.11-1.7.13

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Note: I am on a mac, using LTS Java 17.0.5 (latest), also, I tested this on 11-13 with the exact same log messages so leaving 11 attached below.

I updated Cyclic to 1.7.13 and the server will not start.  I disabled the rest of the mods, still wont start, so I reverted versions until it worked again. The last working version is 1.7.10, 1.7.11-13 does not work standalone.  

Mod File: /Users/joelclendineng/Library/Application Support/PolyMC/instances/FantaEnergy/minecraft/mods/Cyclic-1.18.2-1.7.11.jar
	Failure message: Cyclic (cyclic) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingChangeTargetEvent
	Mod Version: 1.18.2-1.7.11
	Mod Issue URL: https://github.com/Lothrazar/cyclic/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.LivingChangeTargetEvent

Log file link: https://mclo.gs/AWmamk5

**Comment by jclendineng** [comment]
This was resolved by updating forge, for anyone else with this kind of issue, I was using a custom API URL (https://minecraftmachina.github.io/meta-multimc-arm64/) to use ARM specific libs, that was not updated to the latest Forge (it was 3 versions behind), I removed as no longer needed on 1.18.2 and it works.  Completely my fault here, 1.7.13 works as expected with updated Forge.
